create table socks_batch(
                            id int primary key generated by default as identity,
                            color varchar not null,
                            cotton int not null check (cotton > 0 ) check ( cotton <= 100 ),
                            quantity int not null check (quantity > 0)
);