drop table if exists employees;

create table employees(
                          id int primary key generated by default as identity,
                          name varchar not null,
                          surname varchar not null,
                          birth_date date not null,
                          department varchar,
                          salary float
);

insert into employees(name, surname, birth_date, department, salary) values ('Harry', 'Kane', '28.07.1993', 'IT', 92000);
insert into employees(name, surname, birth_date, department, salary) values ('Paolo', 'Maldini', '01.02.1975', 'security', 42000);
insert into employees(name, surname, birth_date, department, salary) values ('Mohammed', 'Salah', '15.06.1992', 'engineering', 70000);
insert into employees(name, surname, birth_date, department, salary) values ('Frank', 'Ribery', '12.04.1983', 'sales', 59000);
insert into employees(name, surname, birth_date, department, salary) values ('Philipp', 'Lahm', '21.08.1981', 'drivers', 30000);
insert into employees(name, surname, birth_date, department, salary) values ('Thomas', 'Muller', '15.05.1989', 'IT', 81000);
insert into employees(name, surname, birth_date, department, salary) values ('Wayne', 'Rooney', '10.10.1988', 'engineering', 75300);
insert into employees(name, surname, birth_date, department, salary) values ('Fernando', 'Torres', '09.12.1988', 'personnel', 50000);
insert into employees(name, surname, birth_date, department, salary) values ('Alexis', 'Sanchez', '05.06.1994', 'IT', 67000);
insert into employees(name, surname, birth_date, department, salary) values ('Alphonso', 'Davies', '02.11.2000', 'security', 39000);